# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/nome-database
spring.datasource.username=tuo-user
spring.datasource.password=tuo-password

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
